/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package videolibrary;

/**
 *
 * @author Andrej
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        addVideoButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        searchVideoButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        importFromODFButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        exportToODFButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        videoTable = new javax.swing.JTable();
        staticLabel = new javax.swing.JLabel();
        numberOfVideosLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        importFromODFMenuButton = new javax.swing.JMenuItem();
        exportToODFMenuButton = new javax.swing.JMenuItem();
        exitMenuButton = new javax.swing.JMenuItem();
        videoMenu = new javax.swing.JMenu();
        addVideoMenuButton = new javax.swing.JMenuItem();
        searchVideoMenuButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Library");

        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        addVideoButton.setText("Add Video");
        addVideoButton.setFocusable(false);
        addVideoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addVideoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addVideoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVideoButtonActionPerformed(evt);
            }
        });
        toolBar.add(addVideoButton);
        toolBar.add(jSeparator1);

        searchVideoButton.setText("Search Video");
        searchVideoButton.setFocusable(false);
        searchVideoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchVideoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(searchVideoButton);
        toolBar.add(jSeparator2);

        importFromODFButton.setText("Import from ODF");
        importFromODFButton.setFocusable(false);
        importFromODFButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        importFromODFButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(importFromODFButton);
        toolBar.add(jSeparator3);

        exportToODFButton.setText("Export to ODF");
        exportToODFButton.setFocusable(false);
        exportToODFButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportToODFButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(exportToODFButton);

        videoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title", "Director(s)", "Actor(s)", "Year", "Country", "Genre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanel.setViewportView(videoTable);

        staticLabel.setText("Number of videos: ");

        numberOfVideosLabel.setText("0");

        fileMenu.setText("File");

        importFromODFMenuButton.setText("Import from ODF");
        fileMenu.add(importFromODFMenuButton);

        exportToODFMenuButton.setText("Export to ODF");
        fileMenu.add(exportToODFMenuButton);

        exitMenuButton.setText("Exit");
        fileMenu.add(exitMenuButton);

        menuBar.add(fileMenu);

        videoMenu.setText("Video");

        addVideoMenuButton.setText("Add Video");
        videoMenu.add(addVideoMenuButton);

        searchVideoMenuButton.setText("Search Video By Title");
        videoMenu.add(searchVideoMenuButton);

        menuBar.add(videoMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staticLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfVideosLabel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staticLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfVideosLabel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addVideoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVideoButtonActionPerformed
        AddVideoDialog dialog = new AddVideoDialog(this, true);
        dialog.setVisible(true); 
    }//GEN-LAST:event_addVideoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVideoButton;
    private javax.swing.JMenuItem addVideoMenuButton;
    private javax.swing.JMenuItem exitMenuButton;
    private javax.swing.JButton exportToODFButton;
    private javax.swing.JMenuItem exportToODFMenuButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton importFromODFButton;
    private javax.swing.JMenuItem importFromODFMenuButton;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel numberOfVideosLabel;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton searchVideoButton;
    private javax.swing.JMenuItem searchVideoMenuButton;
    private javax.swing.JLabel staticLabel;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JMenu videoMenu;
    private javax.swing.JTable videoTable;
    // End of variables declaration//GEN-END:variables
}
